title: "Nahom's Blog"
tagline: "The blog at the corner of the internet"
email: "nahomretebo@gmail.com"
description: "A personal space for technical writings."
url: "https://nonyx777.github.io"
baseurl: ""

github_username: nonyx777
telegram_username: NahomTemesgen
linkedin_url: "https://www.linkedin.com/in/nahomtemesgen/"

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
default_lang: en
timezone: UTC

sass:
  style: compressed

exclude:
  - pages
  - README.md
  - BLOG_GUIDE.md
